num_1 = int(input("Introduce un número: "))
num_2 = int(input("Introduce un número: "))
print("El restultado de la suma es: ", num_1+num_2)
print("El resultado de la multiplicación es: ",num_1*num_2)
print("El resultado de la división es: ", num_1/num_2)
print("El resultado de la división exacta es: ", num_1//num_2)
print("El resultado de la elevar al cuadrado el primer número es: ", num_1**2)
print("El resultado de la elevar al cuadrado el segundo número es: ", num_2**2)
print("El resultado de la elevar al cubo el primer número es: ", num_1**3)
print("El resultado de la elevar al cubo el segundo número es: ", num_2**3)
print("El resultado del módulo es: ", num_1%num_2)